version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin  
    ports:
      - '3306:3306'
    volumes:
      - myvol:/var/lib/mysql
    networks:
      - mynet
  flask-app:
    build:
      context: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: devops
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '5000:5000'
    networks:
      - mynet
    depends_on:
      - mysql
volumes:
  myvol:
networks:
  mynet: 
    driver: bridge


